Try to fix release action

diff --git a/release/action.yml b/release/action.yml
--- a/release/action.yml
+++ b/release/action.yml
@@ -7,20 +7,26 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: Get latest release title
+    - name: Parse latest release
       id: latest
       shell: sh
       env:
         GH_TOKEN: ${{ github.token }}
       run: |
-        version=$(gh release view --json name -q '.name' || echo '0.0.0')
+        version=$(gh release view --json name -q '.name' 2>/dev/null || echo '0.0.0')
+        echo "latest=$version"
+        echo "version=$version" >> "$GITHUB_OUTPUT"
+
+        major="$(echo "$version" | cut -d. -f1)"
+        minor="$(echo "$version" | cut -d. -f2)"
+        patch="$(echo "$version" | cut -d. -f3)"
         {
-          major="$(echo "$version" | cut -d. -f1)"
-          minor="$(echo "$version" | cut -d. -f2)"
-          patch="$(echo "$version" | cut -d. -f3)"
+          echo "major=$major"
+          echo "minor=$minor"
+          echo "patch=$patch"
         } >> "$GITHUB_OUTPUT"
-    - if: ${{ inputs.type == 'major' }}
-      name: Bump major version
+        echo "parsed=$major.$minor.$patch"
+    - name: Bump version
       id: this
       shell: bash
       env:
@@ -29,14 +35,15 @@ runs:
         minor: ${{ steps.latest.outputs.minor }}
         patch: ${{ steps.latest.outputs.patch }}
       run: |
-        if [ "$type" = "major" ]; then
+        if [[ "$type" == "major" ]]; then
           echo "version=$((major + 1)).0.0" >> "$GITHUB_OUTPUT"
-        fi
-        if [ "$type" = "minor" ]; then
+        elif [[ "$type" == "minor" ]]; then
           echo "version=$major.$((minor + 1)).0" >> "$GITHUB_OUTPUT"
-        fi
-        if [ "$type" = "patch" ]; then
+        elif [[ "$type" == "patch" ]]; then
           echo "version=$major.$minor.$((patch + 1))" >> "$GITHUB_OUTPUT"
+        else
+          echo "Invalid type: $type" >&2
+          exit 1
         fi
     - name: Tag current commit
       id: tagger
@@ -45,6 +52,7 @@ runs:
         semver: ${{ steps.this.outputs.version }}
       run: |
         tag="v$semver"
+        echo "this=$tag"
         git tag "$tag"
         git push origin "$tag"
         echo "tag=$tag" >> "$GITHUB_OUTPUT"
