Add enforce input

diff --git a/require-semver-label/action.yml b/require-semver-label/action.yml
--- a/require-semver-label/action.yml
+++ b/require-semver-label/action.yml
@@ -1,6 +1,9 @@
 name: Require Semver Label
 description: "Ensures PR has exactly one semver label (major, minor, or patch)"
 inputs:
+  enforce:
+    description: "Whether to fail upon missing semver label"
+    required: true
   error-message:
     description: "Message to echo upon failure"
     required: false
@@ -39,16 +42,22 @@ runs:
         fail-on-match: ${{ steps.minor.outputs.match == 'true' || steps.major.outputs.match == 'true' }}
 
     - if: ${{ steps.major.outputs.match == 'false' && steps.minor.outputs.match == 'false' && steps.patch.outputs.match == 'false' }}
+      id: failure
       name: Fail if no semver label matched
       shell: sh
       env:
         ERROR_MESSAGE: ${{ inputs.error-message }}
+        ENFORCE: ${{ inputs.enforce }}
       run: |
-        echo "Error: $ERROR_MESSAGE"
-        exit 1
+        if [ "$ENFORCE" == "true" ]; then
+          echo "Error: $ERROR_MESSAGE"
+          exit 1
+        fi
+        echo "skipped=true" >> "$GITHUB_OUTPUT"
 
     # This is not baked into output value to avoid falsely setting release type if a step fails
-    - name: Set output
+    - if: steps.fail.outputs.skipped != 'true'
+      name: Set output
       id: release
       shell: sh
       run: |
